# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-28 05:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='airMach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airpressure', models.IntegerField()),
                ('now', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='autoSwitch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light', models.IntegerField()),
                ('water', models.IntegerField()),
                ('elec', models.IntegerField()),
                ('fan', models.IntegerField()),
                ('now', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='boiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField()),
                ('airpressure', models.IntegerField()),
                ('waterpressure', models.IntegerField()),
                ('elec', models.IntegerField()),
                ('now', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='configsun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunmax', models.IntegerField(verbose_name='光照上限')),
                ('sunmin', models.IntegerField(verbose_name='光照下限')),
                ('now', models.DateTimeField(default=django.utils.timezone.now, verbose_name='设置时间')),
            ],
            options={
                'verbose_name': '光照设置',
            },
        ),
        migrations.CreateModel(
            name='configtemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperaturemax', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='温度上限')),
                ('temperaturemin', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='温度下限')),
                ('now', models.DateTimeField(default=django.utils.timezone.now, verbose_name='设置时间')),
            ],
            options={
                'verbose_name': '温度设置',
            },
        ),
        migrations.CreateModel(
            name='configwater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waterpressuremax', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='水压上限')),
                ('waterpressuremin', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='水压下限')),
                ('now', models.DateTimeField(default=django.utils.timezone.now, verbose_name='设置时间')),
            ],
            options={
                'verbose_name': '水压设置',
            },
        ),
        migrations.CreateModel(
            name='elecColorCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red', models.CharField(max_length=30)),
                ('yellow', models.CharField(max_length=30)),
                ('blue', models.CharField(max_length=30)),
                ('green', models.CharField(max_length=30)),
                ('now', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='elecMachline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField()),
                ('daily', models.IntegerField()),
                ('total', models.IntegerField()),
                ('disrate', models.IntegerField()),
                ('totaltime', models.IntegerField()),
                ('stoptime', models.IntegerField()),
                ('alerttimes', models.IntegerField()),
                ('repairtime', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='elecTimeCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red', models.CharField(max_length=30)),
                ('yellow', models.CharField(max_length=30)),
                ('blue', models.CharField(max_length=30)),
                ('green', models.CharField(max_length=30)),
                ('randy', models.CharField(max_length=30)),
                ('now', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='factoryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=4)),
                ('humidity', models.DecimalField(decimal_places=1, max_digits=4)),
                ('sun', models.IntegerField()),
                ('co2', models.IntegerField()),
                ('PM', models.DecimalField(decimal_places=1, max_digits=3)),
                ('waterpressure', models.DecimalField(decimal_places=3, max_digits=4)),
                ('now', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='fireProSys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waterpressure', models.IntegerField()),
                ('now', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='lightStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid', models.IntegerField()),
                ('status_change', models.TextField()),
                ('now', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='pipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.IntegerField()),
                ('pressure', models.IntegerField()),
                ('now', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='rotorColorCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red', models.TextField()),
                ('yellow', models.TextField()),
                ('blue', models.TextField()),
                ('green', models.TextField()),
                ('now', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='rotorLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runtime', models.IntegerField()),
                ('runtimes', models.IntegerField()),
                ('wrongtime', models.IntegerField()),
                ('wrongtimes', models.IntegerField()),
                ('repairtime', models.IntegerField()),
                ('repairtimes', models.IntegerField()),
                ('waittime', models.IntegerField()),
                ('waittimes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='rotorTimeCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red', models.CharField(max_length=30)),
                ('yellow', models.CharField(max_length=30)),
                ('blue', models.CharField(max_length=30)),
                ('green', models.CharField(max_length=30)),
                ('now', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='sendtomqtt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s1', models.CharField(max_length=6)),
                ('s2', models.CharField(max_length=6)),
                ('s3', models.CharField(max_length=6)),
                ('s4', models.CharField(max_length=6)),
                ('now', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='switchcontrol1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch1', models.IntegerField(default=2)),
                ('now', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='switchcontrol2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch2', models.IntegerField(default=2)),
                ('now', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='switchcontrol3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch3', models.IntegerField(default=2)),
                ('now', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='switchcontrol4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch4', models.IntegerField(default=2)),
                ('now', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='topicGet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid', models.CharField(max_length=10)),
                ('ch', models.CharField(max_length=10)),
                ('m', models.CharField(max_length=10)),
                ('ts', models.DateTimeField()),
                ('s', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='waterTower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(decimal_places=3, max_digits=4)),
                ('ph', models.IntegerField()),
                ('flow', models.IntegerField()),
                ('now', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
