# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-23 08:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configsun',
            options={'verbose_name': '光照设置'},
        ),
    ]
