# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-31 03:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightstatus',
            name='now',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 31, 11, 29, 12, 543869)),
        ),
    ]
