# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-31 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20170831_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightstatus',
            name='now',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
