# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20170823_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='factorydata',
            name='switch1',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='factorydata',
            name='switch2',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='factorydata',
            name='switch3',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='factorydata',
            name='switch4',
            field=models.IntegerField(default=2),
        ),
    ]
