# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 02:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20170824_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='switchcontrol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch1', models.IntegerField(default=2)),
                ('switch2', models.IntegerField(default=2)),
                ('switch3', models.IntegerField(default=2)),
                ('switch4', models.IntegerField(default=2)),
                ('now', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='factorydata',
            name='switch1',
        ),
        migrations.RemoveField(
            model_name='factorydata',
            name='switch2',
        ),
        migrations.RemoveField(
            model_name='factorydata',
            name='switch3',
        ),
        migrations.RemoveField(
            model_name='factorydata',
            name='switch4',
        ),
    ]
